apiVersion: v1
kind: Service
metadata:
  name: tailwind-service
spec:
  type: NodePort
  selector:
    app: tailwind-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
